In [2]:
import numpy as np

a = [9,3,3,5]
print(a)
print(np.array(a))  # Converting list into numpy array



[9, 3, 3, 5]
[9 3 3 5]


In [3]:
import numpy as np

a= np.array(['FCAIT','FCT','FET'])

print(type(a))

print(a)


<class 'numpy.ndarray'>
['FCAIT' 'FCT' 'FET']


In [4]:
#arange(start,end,step) function will create NumPy array starting from start till end (not included) with specified steps.
import numpy as np

b = np.arange(0,10,1)

print(b)


[0 1 2 3 4 5 6 7 8 9]


In [5]:
#zeros(n) function will return NumPy array of given shape, filled with zeros.
import numpy as np

c = np.zeros(3)

print(c)

c1 = np.zeros((3,3)) #have to give as tuple

print(c1)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
import numpy as np

c = np.ones(3)

print(c)

c1 = np.ones((3,3)) #have to give as tuple

print(c1)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#eye(n) function will create 2-D NumPy array with ones on the diagonal and zeros elsewhere.
import numpy as np

b1 = np.eye(2)
b = np.eye(3)

print(b1) 
print(b) 

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#linspace(start,stop,num) function will return evenly spaced numbers over a specified interval.
import numpy as np

c = np.linspace(0,1,11)

print(c)

#Note: in arange function we have given start, stop & step, whereas in lispace function 
#we are giving start,stop & number of elements we want.

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [11]:
#min() function will return the minimum value from the ndarray, there are two ways in which we
#can use min function, example of both ways are given below.
import numpy as np

l = [1,5,3,8,2,3,6,7,5,2,9,11,2,5,3,4,8,9,3,1,9,3]

a = np.array(l)

print('Min way1 = ',a.min())

print('Min way2 = ',np.min(a))

#replace min to max for max value

Min way1 =  1
Min way2 =  1


In [12]:
#Aggregations
l = [7,5,3,1,8,2,3,6,11,5,2,9,10,2,5,3,7,8,9,3,1,9,3]

a = np.array(l)

print('Min = ',a.min())

print('ArgMin = ',a.argmin())

print('Max = ',a.max())

print('ArgMax = ',a.argmax())

print('Sum = ',a.sum())

print('Mean = ',a.mean())

print('Std = ',a.std())

Min =  1
ArgMin =  3
Max =  11
ArgMax =  8
Sum =  122
Mean =  5.304347826086956
Std =  3.042235771223635


In [13]:
#When we apply aggregate functions with multidimensional ndarray, 
#it will apply aggregate function to all its dimensions (axis).
array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('sum = ',array2d.sum())

sum =  45


In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4])

print("shape a:{}".format(a.shape))
print("ndim {}".format(a.ndim))
print("size {}".format(a.size))
print(f"dtype {a.dtype}")
print(f"itemsize {a.itemsize}")
print(f"data {a.data}")

shape a:(5,)
ndim 1
size 5
dtype int64
itemsize 8
data <memory at 0x1048e6980>


In [3]:
a1=np.array([[2,3,4,5],
             [1,4,7,6]])
a2=np.array([[1,1,1],[1,1,1]])
#add(), subtract(),mod(),reminder(),multiply(),divide(), power(),absolute()


sliced_arr=a1[:2,:2]
print(sliced_arr)

[[2 3]
 [1 4]]


In [5]:
index_arr=a1[[1,1],[2,1]]
print(index_arr)print(a1.sum())

[7 4]


In [6]:
print(a1.sum())

32


In [20]:
arr=np.array([[25,64],[89,36]])
print(arr.sum())     # Calculates the sum of all elements in the array


214


In [19]:
print(np.sqrt(arr))  # Calculates the square root of each element in the array (element-wise)

[4.79583152 5.83095189 6.70820393 8.18535277]


In [21]:
print(arr.T)  # Transposes the array (rows become columns and columns become rows)

[[25 89]
 [64 36]]


In [22]:
b1=np.array([[2,3],[4,5]])
b2=np.array([[5,6],[7,8]])
matrix_multi=np.dot(b1,b2)
print(matrix_multi) # Performs matrix multiplication between b1 and b2

[[31 36]
 [55 64]]


In [24]:
#zeros(n) function will return NumPy array of given shape, filled with zeros.
import numpy as np

c = np.zeros(3)

print(c)

c1 = np.zeros((3,3)) #have to give as tuple

print(c1)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
bool = np.array([[True, True],
                 [False, True]])

print("all() with axis none", np.all(bool))          # Checks if all elements in the entire array are True
print("all() with axis 0", np.all(bool, axis=0))     # Checks column-wise if all values are True
# any()

all() with axis none False
all() with axis 0 [False  True]


In [26]:
#arange(start,end,step) function will create NumPy array starting from start till end (not included) with specified steps.
import numpy as np

b = np.arange(0,10,1)

print(b)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
temp = np.arange(9)
print(temp)                 # Creates an array with values from 0 to 8

re = temp.reshape(3, 3)
print(re)                   # Reshapes the 1D array into a 3×3 matrix

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
print(np.take(re, [0, 1], axis=1))   # Selects columns at index 0 and 1 from the arrayaxis=1 means columns.
#[0,1] means it takes the first and second columns.

[[0 1]
 [3 4]
 [6 7]]


In [14]:
x=np.array([[12,23],[23,34]])
y=np.array([[56,67],[78,89]])
z=np.array([[32,43],[54,65]])
v=np.vstack((x,y,z))
h=np.hstack((x,y,z))

print("vstack:",v)
print("hstack:",h)

vstack: [[12 23]
 [23 34]
 [56 67]
 [78 89]
 [32 43]
 [54 65]]
hstack: [[12 23 56 67 32 43]
 [23 34 78 89 54 65]]


In [34]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

result = np.hsplit(arr, 2)
print(result)        # Splits the array horizontally into 2 equal parts
print("===================")
v_split = np.vsplit(arr, 2)
print("vsplit:", v_split)   # Splits the array vertically into 2 equal parts

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
vsplit: [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [38]:
print(np.exp(23))

9744803446.248903


In [17]:
arr=np.array([23,34,45,67])
print("Sqrt: ",np.sqrt(arr))#Returns the square root of each element 
print("Exp: ",np.exp(arr))     #Returns the exponentials of each element
#In NumPy, exponentials mean raising the mathematical constant e to the power of each element in the array.
print("Sin: ",np.sin(arr))     #Returns the sin of each element
print("Cos: ",np.cos(arr))     #Returns the cosine of each element
print("Log: ",np.log(arr))     #Returns the logarithm of each element
print("Sum: ",np.sum(arr))     #Returns the sum total of elements in the array
print("Std: ",np.std(arr))     #Returns the standard deviation of in the array

Sqrt:  [4.79583152 5.83095189 6.70820393 8.18535277]
Exp:  [9.74480345e+09 5.83461743e+14 3.49342711e+19 1.25236317e+29]
Sin:  [-0.8462204   0.52908269  0.85090352 -0.85551998]
Cos:  [-0.53283302 -0.84857027  0.52532199 -0.5177698 ]
Log:  [3.13549422 3.52636052 3.80666249 4.20469262]
Sum:  169
Std:  16.269219403523945


In [40]:
print("random: {}\n".format(np.random.random(20)));
#→ Generates 20 random decimal numbers
#→ Each value is between 0.0 and 1.0 (1 is not included)

print("rand: {}\n".format(np.random.rand(3, 4)));
#→ Generates a 2D array (matrix) with 3 rows and 4 columns
#→ Each value is a random decimal between 0 and 1

print("randint: {}\n".format(np.random.randint(0, 100, 20)));
#→ Generates 20 random integers
#→ Values range from 0 to 99
#→ 0 is included, 100 is excluded

print("permutation: {}\n".format(np.random.permutation(np.arange(20))));
#→ Shuffles these numbers randomly
#→ Each number appears exactly once (no repetition)

random: [0.34943464 0.74982571 0.58528076 0.51718906 0.21913332 0.63428205
 0.2210282  0.90872173 0.02968344 0.73858985 0.73556124 0.12968954
 0.28998079 0.72502725 0.90370899 0.22097409 0.02410401 0.29005353
 0.50316198 0.57030172]

rand: [[0.67511217 0.27264457 0.17115874 0.91252085]
 [0.52784011 0.67584122 0.23864419 0.18282416]
 [0.04094775 0.89291966 0.78929199 0.61286127]]

randint: [65 22 51 54 33 48 90 80 23 12 45 17 42 88 27 29 16  0 45  1]

permutation: [14  7 15  6 11  2 10 17 13  4  0 16 12  9  3 19  1 18  8  5]

