In [ ]:
import numpy as np

NumPy is used to perform fundamental scientific computing.

NumPy library provides the means for performing n-dimensional array manipulation, which is
critical for data science work.

NumPy provides functions that include support for linear algebra, Fourier transformation,
random-number generation and many more..

The most important object defined in NumPy is an N-dimensional array type called ndarray.

It describes the collection of items of the same type, Items in the collection can be accessed
using a zero-based index.

An instance of ndarray class can be constructed in many different ways, the basic ndarray can
be created as below.

In [ ]:
import numpy as np

a= np.array(['FCAIT','FCT','FET'])

print(type(a))

print(a)

<class 'numpy.ndarray'>
['FCAIT' 'FCT' 'FET']


In [ ]:
#arange(start,end,step) function will create NumPy array starting from start till end (not included) with specified steps.
import numpy as np

b = np.arange(0,10,1)

print(b)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#zeros(n) function will return NumPy array of given shape, filled with zeros.
import numpy as np

c = np.zeros(3)

print(c)

c1 = np.zeros((3,3)) #have to give as tuple

print(c1)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

c = np.ones(3)

print(c)

c1 = np.ones((3,3)) #have to give as tuple

print(c1)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#eye(n) function will create 2-D NumPy array with ones on the diagonal and zeros elsewhere.
import numpy as np

b = np.eye(2)
#b = np.eye(3)

print(b)

[[1. 0.]
 [0. 1.]]


In [ ]:
#linspace(start,stop,num) function will return evenly spaced numbers over a specified interval.
import numpy as np

c = np.linspace(0,1,11)

print(c)

#Note: in arange function we have given start, stop & step, whereas in lispace function 
#we are giving start,stop & number of elements we want.

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
#min() function will return the minimum value from the ndarray, there are two ways in which we
#can use min function, example of both ways are given below.
import numpy as np

l = [1,5,3,8,2,3,6,7,5,2,9,11,2,5,3,4,8,9,3,1,9,3]

a = np.array(l)

print('Min way1 = ',a.min())

print('Min way2 = ',np.min(a))

Min way1 =  1
Min way2 =  1


In [ ]:
import numpy as np

l = [1,5,3,8,2,3,6,7,5,2,9,11,2,5,3,4,8,9,3,1,9,3]

a = np.array(l)

print('Max way1 = ',a.max())

print('Max way2 = ',np.max(a))

Max way1 =  11
Max way2 =  11


In [ ]:
#Aggregations
l = [7,5,3,1,8,2,3,6,11,5,2,9,10,2,5,3,7,8,9,3,1,9,3]

a = np.array(l)

print('Min = ',a.min())

print('ArgMin = ',a.argmin())

print('Max = ',a.max())

print('ArgMax = ',a.argmax())

print('Sum = ',a.sum())

print('Mean = ',a.mean())

print('Std = ',a.std())

Min =  1
ArgMin =  3
Max =  11
ArgMax =  8
Sum =  122
Mean =  5.304347826086956
Std =  3.042235771223635


In [ ]:
#When we apply aggregate functions with multidimensional ndarray, it will apply aggregate function to all its dimensions (axis).
import numpy as np

array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('sum = ',array2d.sum())

sum =  45


In [ ]:
import numpy as np

array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('sum (cols)= ',array2d.sum(axis=0)) #Vertical

print('sum (rows)= ',array2d.sum(axis=1)) #Horizontal

sum (cols)=  [12 15 18]
sum (rows)=  [ 6 15 24]


In [1]:
#Array Shape in NumPy
import numpy as np

b = np.zeros((3,3))

print(b.shape)

(3, 3)


In [8]:
#reshape the array using reshape method of ndarray
import numpy as np

re1 = np.random.randint(1,100,15)

print(re1)

re2 = re1.reshape(5,3)

print(re2)


#Note: the number of elements and multiplication of rows and cols in new array must be equal.

#Example : here we have old one-dimensional array of 10 elements and reshaped shape is (5,2)

#so, 5 * 2 = 10, which means it is a valid reshape

[21 84 93  9 71 88 20 68 22 83 79 47 86 73  6]
[[21 84 93]
 [ 9 71 88]
 [20 68 22]
 [83 79 47]
 [86 73  6]]


In [12]:
#Single V/S Double bracket notations
import numpy as np
arr =np.array([['a','b','c'],['d','e','f'],['g','h','i']])

print(arr)

print('double = ',arr[2][0]) # double bracket notaion

print('single = ',arr[2,0]) # single bracket notation

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]
double =  g
single =  g


In [11]:
#Slicing ndarray
#Similar to Python List, we can use same syntax array[start:end:step] to slice ndarray.
#Default start is 0
#Default end is length of the array
#Default step is 1

import numpy as np

arr =np.array(['a','b','c','d','e','f','g','h'])

print(arr[2:5])
print(arr[:5])
print(arr[5:])
print(arr[2:7:2])
print(arr[::-1])

['c' 'd' 'e']
['a' 'b' 'c' 'd' 'e']
['f' 'g' 'h']
['c' 'e' 'g']
['h' 'g' 'f' 'e' 'd' 'c' 'b' 'a']
